Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113306
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113466
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113607
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "C:\Program Files\Thong\hethong\WebDjango\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\MT GAMING\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: authentication/employee_verified.html
"GET /verifed/ HTTP/1.1" 500 113327
Internal Server Error: /verifed/
Traceback (most recent call last):
  File ".\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 3: 'block'. Looking for one of: endblock.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 3: 'block'. Looking for one of: endblock.
Internal Server Error: /verifed/
Traceback (most recent call last):
  File ".\authentication\views\employee_views.py", line 105, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', context)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 5: 'block'. Looking for one of: endblock.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\employee_views.py", line 117, in employee_verified_view
    return render(request, 'authentication/employee_verified.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 518, in parse
    self.unclosed_block_tag(parse_until)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 581, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 5: 'block'. Looking for one of: endblock.
Internal Server Error: /
Traceback (most recent call last):
  File ".\authentication\views\home_views.py", line 335, in home_view
    return render(request, 'authentication/home.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1491, in do_with
    nodelist = parser.parse(("endwith",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1488, in do_with
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'with' received an invalid token: '//'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".\authentication\views\home_views.py", line 352, in home_view
    return render(request, 'authentication/home.html', {
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 853, in do_for
    nodelist_loop = parser.parse(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1491, in do_with
    nodelist = parser.parse(("endwith",))
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\template\defaulttags.py", line 1488, in do_with
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'with' received an invalid token: '//'
Internal Server Error: /home/
Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File ".\authentication\views\login_views.py", line 167, in verify_otp_view
    if otp_expiry and current_time > otp_expiry:
TypeError: can't compare offset-naive and offset-aware datetimes
Internal Server Error: /home/
Traceback (most recent call last):
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\mt gaming\appdata\local\programs\python\python38\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File ".\authentication\views\login_views.py", line 169, in verify_otp_view
    if otp_expiry and current_time > otp_expiry:
TypeError: can't compare offset-naive and offset-aware datetimes
